import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Head from "next/head";
// import { Header } from "./_components/Header";
// import Footer from "./_components/Footer";
// import { CartContext } from "./_context/CartContext";
import ClientLayout from "./_components/ClientLayout";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${roboto.variable} ${geistMono.variable} antialiased`}
        >
          <ClientLayout>{children}</ClientLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}
